products/urls.py
from django.urls import path
from rest_framework.urlpatterns import format_suffix_patterns

from . import views

app_name = 'products'
urlpatterns = [
        path('', views.IndexView.as_view(), name='index'),
        path('<int:product_id>', views.detail, name='detail'),
        path('json/', views.JsonList.as_view(), name='JsonList'),
        path('json/<pk>', views.JsonDetail.as_view(), name='JsonDetail'),
]

urlpatterns = format_suffix_patterns(urlpatterns)

products/models.py
from django.db import models

class Product(models.Model):
    name = models.CharField(max_length=200, default='Product')
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=6, default=0.0, decimal_places=2)

    def __str__(self):
        return self.name

products/views.py
from django.shortcuts import render, redirect
from django.views import generic
from django.contrib.auth.models import User

from django.views.decorators.csrf import csrf_exempt
from rest_framework.parsers import JSONParser
from rest_framework import status
from rest_framework.decorators import api_view
from rest_framework.response import Response
from django.http import Http404
from rest_framework.views import APIView
from rest_framework import mixins
from rest_framework import generics

from .models import Product
from cart.forms import CartItemForm
from cart.models import CartItem

from .serializers import ProductSerializer

class IndexView(generic.ListView):
    template_name = 'products/index.html'
    queryset = Product.objects.all()

def detail(request, product_id):
    product = Product.objects.get(pk=product_id)
    user = User.objects.get(username=request.user)

    if request.method == 'POST':
        form = CartItemForm(request.POST)
        if form.is_valid():
            item = CartItem()
            item.user = user
            item.product = product
            item.quantity = form.cleaned_data['quantity']
            item.save()

            return redirect('products:index')

    else:
        form = CartItemForm()

    return render(request, 'products/detail.html', {'form': form, 'product': product, 'user': user})


class JsonList(generics.ListCreateAPIView):
    queryset = Product.objects.all()
    serializer_class = ProductSerializer

class JsonDetail(generics.RetrieveUpdateDestroyAPIView):
    queryset = Product.objects.all()
    serializer_class = ProductSerializer

products/templates/products/detail.html
<h1>{{ product.name }}</h1>
<p>{{ product.description }}</p>
<h3>{{ product.price }}</h3>

<form action="{% url 'products:detail' product.id %}" method="post">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="Add to Cart" />
</form>

<a href="{% url 'products:index' %}">other products</a>

products/templates/products/index.html
{% if product_list %}
<h3><a href="{% url 'cart:index' %}">MyCart</a></h3>
    <ol>
        {% for product in product_list %}
                <li><a href="{% url 'products:detail' product.id %}">{{ product }}</a></li>
        {% endfor %}
    </ol>
{% else %}
    <p> There is no products. </p>
{% endif %}